/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(aep_metric.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9cf36021a25b2dc26911e75cb5c1252c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aep/aep_metric.h>
// pydoc.h is automatically generated in the build directory
#include <aep_metric_pydoc.h>

void bind_aep_metric(py::module& m)
{

    using aep_metric    = ::gr::aep::aep_metric;


    py::class_<aep_metric, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<aep_metric>>(m, "aep_metric", D(aep_metric))

        .def(py::init(&aep_metric::make),
           py::arg("M"),
           py::arg("num_sc"),
           py::arg("nmem"),
           py::arg("thresh"),
           D(aep_metric,make)
        )
        



        ;




}








