/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(aep_channel_processing.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(be53f3f26ab9026586f9df0a2f786529)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aep/aep_channel_processing.h>
// pydoc.h is automatically generated in the build directory
#include <aep_channel_processing_pydoc.h>

void bind_aep_channel_processing(py::module& m)
{

    using aep_channel_processing    = ::gr::aep::aep_channel_processing;


    py::class_<aep_channel_processing, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<aep_channel_processing>>(m, "aep_channel_processing", D(aep_channel_processing))

        .def(py::init(&aep_channel_processing::make),
           py::arg("M"),
           py::arg("num_sc"),
           py::arg("thresh"),
           D(aep_channel_processing,make)
        )
        



        ;




}








