/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(spatial_cov_per_sc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1a6eb54f5dbfb971a26075983c647b0a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aep/spatial_cov_per_sc.h>
// pydoc.h is automatically generated in the build directory
#include <spatial_cov_per_sc_pydoc.h>

void bind_spatial_cov_per_sc(py::module& m)
{

    using spatial_cov_per_sc    = ::gr::aep::spatial_cov_per_sc;


    py::class_<spatial_cov_per_sc, gr::sync_decimator,
        std::shared_ptr<spatial_cov_per_sc>>(m, "spatial_cov_per_sc", D(spatial_cov_per_sc))

        .def(py::init(&spatial_cov_per_sc::make),
           py::arg("M"),
           py::arg("fft_size"),
           py::arg("num_avg"),
           D(spatial_cov_per_sc,make)
        )
        



        ;




}








